version: "3"

services:
  db:
    image: postgres:12.4
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema_design/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    expose:
      - 5432
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/admin_movies/movies_admin/static/
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - static_volume:/var/html/static/
    depends_on:
      - web
    ports:
      - "80:80"
    restart: always


volumes:
  postgres_data:
  static_volume: